---
title: "Prepare data for PHESANT analysis"
---

```{r}
source('0.0.- Setup.R')
```

```{r}
pheno_vars <- read_csv(file.path(
  root_fd, 'data/releases/ukb_ids_releases.csv'),
  col_types = cols()) |> 
  arrange(category) |> 
  mutate(cat_id=dense_rank(category)) |> relocate(cat_id)
```

```{r}
phesant_covars <- pheno_vars |>
  filter(id %in% c(31, 21022, 22009, 22192)) |>
  select(-cat_id)
```

```{r}
phesant_control <- pheno_vars |>
  filter(cat_id == 19) |>
  select(-cat_id)
```

```{r}
phesant_control |> 
  write_csv(file.path(root_fd, 'data/phesant/input/phesant_blood.csv'))
```

```{r}
phesant_vars <- pheno_vars |>
  filter(cat_id %in% c(
    7, 8, 16, 17, 19, 21, 24, 25, 27, 28, 32, 34, 35, 37, 40, 41,
    42, 43, 44, 46, 48, 49, 51, 54, 55, 58, 59, 65, 66, 69, 70, 72,
    74, 77, 78, 79, 84, 92, 94, 95, 97, 98, 101, 103, 104, 105, 107,
    111, 112, 113, 114, 119, 121, 125, 135, 136, 137, 143, 144, 145,
    149, 150, 156, 159, 162, 167, 175, 176)) |>
  filter((cat_id != 16 | id == 189),
         (cat_id != 21 | grepl('automated', title)),
         (cat_id != 59 | id %in% c(
           129, 130, 1677, 1687, 1687, 1707, 1777, 1787, 20022)),
         (cat_id != 79 | id == 22024),
         (cat_id != 84 | id == 2247),
         ! grepl('record', title),
         ! grepl('Reason', title),
         ! grepl('Source', title),
         ! grepl('Interpolated', title), 
         ! grepl('Method of recording', title),
         ! grepl('(pilot)', title)) |>
  select(-cat_id)
```

```{r}
phesant_vars |> 
  write_csv(file.path(
    root_fd, 'data/phesant/input/phesant_vars_with_bc.csv'),
    na = "")
```

```{r}
read_csv(file.path(
  root_fd, 'data/pheno/ukb_gwas_covars.csv'),
  col_types = cols()) |>
  inner_join(
    read_csv(file.path(
      root_fd, 'data/pheno/ukb_participants_latest.csv'),
      col_types = cols()),
    by = 'eid') |>
  select(-Height, -starts_with('Blood'), -CN) |>
  rename(AgeSq=`Age Sq`, AdjTL=`Adj TL`) |>
  write_csv(file.path(
    root_fd, 'data/phesant/input/phesant_cov.csv'),
    na = '')
```

```{r}
read_csv(file.path(
  root_fd, 'data/pheno/ukb_blood_counts.csv'),
  col_types = cols())  |>
  inner_join(
    read_csv(file.path(
      root_fd, 'data/pheno/ukb_participants_latest.csv'),
      col_types = cols()),
    by = 'eid') |>
  inner_join(read_csv(file.path(
    root_fd, 'data/pheno/ukb_gwas_covars.csv'),
    col_types = cols()) |>
               select(eid, CN),
             by = 'eid') |>
  mutate(NLR = `Neutrophil #` / `Lymphocyte #`,
         PLR = `Platelet #` / `Lymphocyte #`,
         SII = (`Neutrophil #` * `Platelet #`) / `Lymphocyte #`) |>
  select(eid, CN, NeutroCount = `Neutrophil #`, PlatCount = `Platelet #`,
         LymphCount = `Lymphocyte #`, NLR, PLR, SII) |>
  write_csv(file.path(
    root_fd, 'data/phesant/input/phesant_traits.csv'), na = '')
```

### rDNA ratios

```{r}
read_csv(file.path(
  root_fd, 'data/pheno/ukb_blood_counts.csv'),
  col_types = cols())  |>
  inner_join(
    read_csv(file.path(
      root_fd, 'data/pheno/ukb_participants_latest.csv'),
      col_types = cols()),
    by = 'eid') |>
  inner_join(read_csv(file.path(
    root_fd, 'data/pheno/ukb_gwas_covars.csv'),
    col_types = cols()) |>
      select(eid, CN),
    by = 'eid') |>
  inner_join(read_csv(file.path(
    root_fd, 'data/cn/ukb_5s.csv'), col_types = cols()),
             by = 'eid') |>
  mutate(rRNA_Ratio = CN / ratio_all_5s) |>
  select(eid, rRNA_Ratio) |>
  write_csv(file.path(
    root_fd, 'data/phesant/input/phesant_rrna_ratio.csv'),
    na = '')
```

